apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      terminationGracePeriodSeconds: 30
      containers:
      - name: frontend
        image: nareshbabu1991/three-tier-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000


apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
  selector:
    role: frontend
