apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
  selector:
    role: frontend
